name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "2.7"
          - "3.6"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements_dev.txt -e .
      - run: |
          pytest MicroInverse #python setup.py test